### PR TITLE
SubscriptionChangeMutation

### PR DESCRIPTION
**Pull request by elbotho**
Draft for a mutation to add, update and remove subscriptions.

Notes:
- Did not add a route, since we likely change to messages
- Feel free to change the naming (and everything ;)
- slightly preferred to have only one message for all actions, but could also be split up (would maybe split it up for the graphql mutations?)

### CODE REVIEW

**Comment by inyono** [comment]
What are the planned mutations in api.serlo.org?

**Comment by elbotho** [comment]
Idea:
Maybe just a `setSubsriptionState` would be most consistent and simple:
With an input of `{id, subscribe, sendEmail}`
Otherwise we would need a delete, add and change mutation, which seems a bit much for a simple thing that's likely to change in somewhat near the future.

What do you think?

**Comment by inyono** [comment]
Okay. I'm fine with either
```graphql
mutation {
  uuid {
    setSubscribe(input: $input)
  }
}
```
(with https://github.com/serlo/api.serlo.org/issues/101 in mind) or
```graphql
mutation {
  subscription {
    set(input: $input)
  }
}
```
Your pick, @elbotho 😉

**Comment by elbotho** [comment]
In this case, let's go with the second option.

**Review by inyono — APPROVED** [review]

**Comment by elbotho** [comment]
✨  Thanks!

**Pull request merged**
