### PR TITLE
Upgrade Node to version 16

### PR DESCRIPTION
**Pull request by hugotiburtino**

### CODE REVIEW

**Comment by hugotiburtino** [comment]
Needs resolution of problem with node-gyp (see Pacts / test at Actions.)

**Comment by kulla** [comment]
> Needs resolution of problem with node-gyp (see Pacts / test at Actions.)

In this PR `yarn.lock` got deleted. Maybe not intended... :smile:

**Comment by hugotiburtino** [comment]
> In this PR yarn.lock got deleted. Maybe not intended... 😄
😁 I've chosen the strategy to refresh it entirely with `yarn install`.

Anyways, I reinserted the old `yarn.lock` and it was still not working.
I installed nodegit (that uses node-gyp) as a dependecy, upgraded the lock file, and removed nodegit, and although it works now locally it doesn't in Actions.

There is an old issue about nodegit and node 16. https://github.com/nodegit/nodegit/issues/1840

**Comment by kulla** [comment]
Okay, I see. We need to go through the dependencies anyway and update them... Maybe we can replace `nodegit`?!

**Comment by hugotiburtino** [comment]
> Okay, I see. We need to go through the dependencies anyway and update them... Maybe we can replace nodegit?!

It is not our direct dependency, but a dependency from a dependency. Fortunately, one can find it only at inyono/changelog and Jonas has already released the version 0.4.0 of it, which does not use nodegit.  I've upgraded it and it works now.

**Review by kulla — APPROVED** [review]

**Pull request merged**
